# Generated by Django 3.2.5 on 2021-07-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
