# Generated by Django 3.2.5 on 2021-07-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0002_auto_20210707_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(default='fortnite', max_length=255, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='telnum',
            field=models.CharField(default='5438678945', max_length=10, verbose_name='Telephone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medneed',
            field=models.CharField(default='Borken booons', max_length=255, verbose_name='Medical Needs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='resolve',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='Doctor', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='Sam', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telnum',
            field=models.CharField(max_length=10, verbose_name='Telephone Number'),
        ),
    ]
