# Generated by Django 3.2.5 on 2021-07-11 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0004_auto_20210711_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='dateappt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appt',
            name='lastapp',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of last appointment.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appt',
            name='location',
            field=models.CharField(default='Canada', max_length=255, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appt',
            name='patienttools',
            field=models.CharField(default='Toothbrush', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appt',
            name='procedure',
            field=models.CharField(default='tooth removal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appt',
            name='toolsneeded',
            field=models.CharField(default='Hammer', max_length=255),
            preserve_default=False,
        ),
    ]
